### ISSUE TITLE
containsAll not case insensitive

### ISSUE THREAD

**Issue by arcticicestudio** [arcticgrave/icecore-strman#3]
The `containsAll(String, String[])` method is not case insensitive contrary to the description in the JavaDoc.
This can be fixed by passing `false` as parameter to the `contains(String, String[], boolean)` method called in the method body.
```java
return Arrays.stream(needles).allMatch(needle -> contains(value, needle, false));
```

**Comment by shivamagarwal7** [comment]
@arcticicestudio, can I do this?

**Comment by shivamagarwal7** [comment]
I see its already fixed.

**Comment by arcticicestudio** [comment]
Hi @sa160690 , thanks for the offer, almost forgot that this project still exists :smile: 
Anyway, the library was never really used and will be achieved/deleted. Please migrate to more actively maintained projects like [shekhargulati/strman-java](https://github.com/shekhargulati/strman-java).
